spring:
  batch:
    initialize-schema: embedded 
  datasource:
    initialization-mode: ALWAYS
    platform: h2
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:pedidosya_jobs;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
  data:
    cassandra:
      contact-points: localhost
      port: 9042
      cluster-name: pedidosya_cluster
      keyspace-name: pedidosya_ks
      schema-action: create-if-not-exists 
  h2:
    console:
      enabled: true
      settings:
        trace: true
        web-allow-others: true
scheduling:
  jobs:
    rating: "*/30 * * * * *"
#  cloud:
#    stream:
#      kafka:
#        binder:
#          brokers: localhost:9092
#          autoCreateTopics: true
#      bindings:
#        events-in:
#          destination: event-bus-in
#          contentType: application/json
#        events-out:
#          destination: event-bus-out
#          contentType: application/json   
    