version: "2.4"
services:
  cassandra-pedidosya:
    build: .
    container_name: cassandra-pedidosya
    image: cassandra:latest
    tty: true
    ports:
    - "7000:7000"
    - "7001:7001"
    - "7199:7199"
    - "9042:9042"
    - "9160:9160"
  kafka-pedidosya:
    build: .
    container_name: kafka-pedidosya
    image: spotify/kafka:latest
    tty: true
    ports:
    - "2181:2181"
    - "9092:9092"

  